# Generated by Django 5.2 on 2025-04-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="images",
            field=models.ImageField(
                default="Images/None/sampleImg.jpg", upload_to="Images"
            ),
        ),
    ]
