# Form implementation generated from reading ui file 'todo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(397, 325)
        self.taskEdit = QtWidgets.QLineEdit(parent=Form)
        self.taskEdit.setGeometry(QtCore.QRect(70, 60, 113, 22))
        self.taskEdit.setObjectName("taskEdit")
        self.addButton = QtWidgets.QPushButton(parent=Form)
        self.addButton.setGeometry(QtCore.QRect(200, 60, 75, 24))
        self.addButton.setObjectName("addButton")
        self.deleteButton = QtWidgets.QPushButton(parent=Form)
        self.deleteButton.setGeometry(QtCore.QRect(280, 60, 75, 24))
        self.deleteButton.setObjectName("deleteButton")
        self.tasklist = QtWidgets.QListWidget(parent=Form)
        self.tasklist.setGeometry(QtCore.QRect(90, 100, 256, 192))
        self.tasklist.setObjectName("tasklist")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addButton.setText(_translate("Form", "Add"))
        self.deleteButton.setText(_translate("Form", "Delete"))
